import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import { Providers } from '@/providers/provider'
import Footer from '@/components/footer'



const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Badaro Eventos',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en" style={{ height: '100%' }}>
      <body className={`${inter.className} h-screen flex flex-col`}>
        <Providers>
          <Header />
          {children}

          <Footer />


        </Providers>
      </body>
    </html>
  )
}
